default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: roomz_development

test:
  <<: *default
  database: roomz_test

production:
  <<: *default
  database: roomz_production
